name: classico
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.5.3+2
  get: ^4.6.5
  provider: ^6.0.5
  google_fonts: ^4.0.3 # Updated to the latest version
  http: ^0.13.5
  flutter_vector_icons: ^2.0.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.1.0
  flutter_svg: ^2.0.5
  flutter_zoom_drawer: ^3.0.4+1
  flutter_chat_bubble: ^2.0.2
  flutter_animate: ^4.1.1+1
  image_cropper: ^3.0.3
  image_picker: ^0.8.7+4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0  # Updated to the latest version

flutter:
  uses-material-design: true

  assets:
    - assets/images/LandingImage.png  # Image for the landing page
    - assets/images/PageTwo.png       # Image for Page Two
    - assets/images/PageThree.png       # Image for Page Two

